export const PRIMARY = "#5d88bd" 
export const PRIMARY_FG = "#ffffff";
export const BACKGROUND = "#ffffff";
export const BORDER = "#dcdcdc";
export const GRAY_128 = "#808080";
export const GRAY_245 = "#f5f5f5";
export const GRAY_250 = "#fafafa";
export const NAV = "#151A25";
export const NAV_FG = "#ffffff";
export const NAV_SEPARATOR = "#454545"; 
export const DANGEROUS = "#dd6a6a";
export const SUCCESS = "#47b385";
export const BACKDROP = "rgba(0, 0, 0, .5)";
